import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";

const sourceDir = path.resolve("data/source");
const browserGeneratedDir = path.resolve("src/content/generated");
const godotGeneratedDir = path.resolve("godot/data/generated");

function stableJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

async function readJson(filename) {
  const filePath = path.join(sourceDir, filename);
  const raw = await fs.readFile(filePath, "utf8");
  return JSON.parse(raw);
}

function buildCampaignIndex(campaignSource) {
  const roomsById = Object.fromEntries(campaignSource.rooms.map((room) => [room.id, room]));
  return {
    ...campaignSource,
    roomsById,
  };
}

function jsModuleBanner(sourceName) {
  return `// Generated by scripts/sync-content.mjs from data/source/${sourceName}\n// Do not edit this file directly.\n\n`;
}

async function writeFile(targetPath, contents) {
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, contents, "utf8");
}

async function writeBrowserModules(campaignSource, devRoomsSource, solutionsSource) {
  const campaignIndex = buildCampaignIndex(campaignSource);
  const campaignModule = `${jsModuleBanner("campaign.json")}export const ACHIEVEMENTS = ${stableJson(campaignSource.achievements).trim()};\nexport const DISTRICTS = ${stableJson(campaignSource.districts).trim()};\nexport const ROOM_DEFS = ${stableJson(campaignSource.rooms).trim()};\nexport const ROOM_LOOKUP = ${stableJson(campaignIndex.roomsById).trim()};\nexport const CAMPAIGN_INDEX = ${stableJson(campaignIndex).trim()};\n`;
  const devRoomsModule = `${jsModuleBanner("dev-rooms.json")}export const THREE_LAYER_PROOF_ROOM = ${stableJson(devRoomsSource.threeLayerProofRoom).trim()};\n`;
  const solutionsModule = `${jsModuleBanner("solutions.json")}export const CANONICAL_SOLUTIONS = ${stableJson(solutionsSource.canonicalSolutions).trim()};\nexport const THREE_LAYER_PROOF_SOLUTION = ${stableJson(solutionsSource.threeLayerProofSolution).trim()};\n`;

  await writeFile(path.join(browserGeneratedDir, "campaign.generated.js"), campaignModule);
  await writeFile(path.join(browserGeneratedDir, "dev-rooms.generated.js"), devRoomsModule);
  await writeFile(path.join(browserGeneratedDir, "solutions.generated.js"), solutionsModule);
}

async function writeGodotJson(campaignSource, devRoomsSource, solutionsSource) {
  await writeFile(
    path.join(godotGeneratedDir, "campaign_index.json"),
    stableJson(buildCampaignIndex(campaignSource))
  );
  await writeFile(path.join(godotGeneratedDir, "dev_rooms.json"), stableJson(devRoomsSource));
  await writeFile(path.join(godotGeneratedDir, "solutions.json"), stableJson(solutionsSource));
}

export async function syncContent() {
  const [campaignSource, devRoomsSource, solutionsSource] = await Promise.all([
    readJson("campaign.json"),
    readJson("dev-rooms.json"),
    readJson("solutions.json"),
  ]);

  await Promise.all([
    writeBrowserModules(campaignSource, devRoomsSource, solutionsSource),
    writeGodotJson(campaignSource, devRoomsSource, solutionsSource),
  ]);

  process.stdout.write("Synced shared content to browser and Godot outputs.\n");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  syncContent().catch((error) => {
    process.stderr.write(`${error.stack || error}\n`);
    process.exitCode = 1;
  });
}
